### ISSUE TITLE
Add JustList: {Water H2O JustSwap List}

### ISSUE THREAD

**Issue by OmJao** [justswaporg/justlists#1645]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://www.tokenh2o.com/justswap.json
JustList Name: Water H2O JustSwap List
Link to the official homepage of the JustList manager: https://www.tokenh2o.com

**Comment by jz2120100058** [comment]
We found that all the tokens in the application List you submitted except “SITE, H20, BXR, OBR, BTCST, BRG” have been included in the Tron Alliance List. Since there is only six new tokens, we suggest adding “SITE, H20, BXR, OBR, BTCST, BRG” to the existing List, such as Tron Alliance List:https://github.com/listtronalliance/tronalliance.

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as the issue has not been replied for more than one month.Please submit again if you would like to apply for a new list.
Finally, thank you again for your application.I hope you are having a great day.
